apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: twitter-migration
  name: twitter-migration
  namespace: gateway
spec:
  progressDeadlineSeconds: 2147483647
  replicas: 1
  revisionHistoryLimit: 2147483647
  selector:
    matchLabels:
      name: twitter-migration
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        name: twitter-migration
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: type
                    operator: In
                    values:
                      - gateway
      containers:
        - args:
            - start
          env:
            - name: PORT
              value: "9000"
            - name: LOGGER_TYPE
              value: console
            - name: NODE_ENV
              value: prod
            - name: PUBLIC_URL
              value: http://production-api.globalforestwatch.org
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  key: CT_MONGO_URI
                  name: control-tower
            - name: GFW_TWITTER_CONSUMER_KEY
              valueFrom:
                secretKeyRef:
                  key: GFW_TWITTER_CONSUMER_KEY
                  name: control-tower
            - name: GFW_TWITTER_CONSUMER_SECRET
              valueFrom:
                secretKeyRef:
                  key: GFW_TWITTER_CONSUMER_SECRET
                  name: control-tower
            - name: RW_TWITTER_CONSUMER_KEY
              valueFrom:
                secretKeyRef:
                  key: RW_TWITTER_CONSUMER_KEY
                  name: control-tower
            - name: RW_TWITTER_CONSUMER_SECRET
              valueFrom:
                secretKeyRef:
                  key: RW_TWITTER_CONSUMER_SECRET
                  name: control-tower
            - name: PREP_TWITTER_CONSUMER_KEY
              valueFrom:
                secretKeyRef:
                  key: PREP_TWITTER_CONSUMER_KEY
                  name: control-tower
            - name: PREP_TWITTER_CONSUMER_SECRET
              valueFrom:
                secretKeyRef:
                  key: PREP_TWITTER_CONSUMER_SECRET
                  name: control-tower
          image: vizzuality/twitter-migration
          imagePullPolicy: Always
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /healthcheck
              port: 9000
              scheme: HTTP
            initialDelaySeconds: 30
            periodSeconds: 15
            successThreshold: 1
            timeoutSeconds: 5
          name: control-tower
          ports:
            - containerPort: 9000
              protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /healthcheck
              port: 9000
              scheme: HTTP
            initialDelaySeconds: 30
            periodSeconds: 15
            successThreshold: 1
            timeoutSeconds: 5
          resources:
            limits:
              cpu: "1"
              memory: 512M
            requests:
              cpu: 350m
              memory: 256M
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: { }
      terminationGracePeriodSeconds: 30
