version: "3"
services:
  test:
    build: .
    ports:
      - "9000:9000"
    container_name: twitter-migration-test
    environment:
      NODE_ENV: test
      PORT: 9000
      PUBLIC_URL: http://localhost:9000
      MONGO_PORT_27017_TCP_ADDR: mongo
      REDIS_URL: redis
      GFW_TWITTER_CONSUMER_KEY: GFW_TWITTER_CONSUMER_KEY
      GFW_TWITTER_CONSUMER_SECRET: GFW_TWITTER_CONSUMER_SECRET
      RW_TWITTER_CONSUMER_KEY: RW_TWITTER_CONSUMER_KEY
      RW_TWITTER_CONSUMER_SECRET: RW_TWITTER_CONSUMER_SECRET
      PREP_TWITTER_CONSUMER_KEY: PREP_TWITTER_CONSUMER_KEY
      PREP_TWITTER_CONSUMER_SECRE: PREP_TWITTER_CONSUMER_SECRE
    command: test
    depends_on:
      - mongo
      - redis
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  mongo:
    image: mongo:3.6.13
    command: --smallfiles
    ports:
      - "27017"

  redis:
    image: redis
    container_name: twitter-migration-redis
    ports:
      - "16379:6379"
    restart: always
