apiVersion: v1
kind: Service
metadata:
  namespace: gateway
  labels:
    name: twitter-migration
  name: twitter-migration
spec:
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 9000
  selector:
    name: twitter-migration
