apiVersion: v1
kind: Service
metadata:
  namespace: gateway
  labels:
    name: control-tower
  name: control-tower
spec:
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 9000
  selector:
    name: control-tower
